package com.shopleech.base.config.type;

/**
 * @author Ahto Jalak
 * @since 05.02.2023
 */
public enum CategoryTypeCode {
    KITCHEN, COOKIES, DRINKS, EGGS, FISH, FLOUR, JUURVILI, KODUMASINAD,
    KYLMIK, LEIB, MARGARIIN, MAYO, MEAT, MEDIA, OIL, OLIVEOIL, OTHEROIL, PAEVALILLEOLI, PIIM, PUUVILI,
    RAPSIOLI, RASVAVOIE, TARBEKAUP, TOIT, TV, VALMISTOIT, VOI, JUUST,
    AUDIO_VIDEO, LONGDRINK, SIIDER, BEER, TEE, KOHV, MAHL, JAHU, KARASTUSJOOK, KOKTEIL,
    BEAUTY_HEALTH,
    FOOD,
    CAMERA_PHOTO,
    COMPUTERS,
    TOOLS,
    FASHION,
    GAMES,
    GARDEN,
    HOME,
    KIDS,
    PHONES,
    SPORTS,
    CARS,
    HOUSEHOLD,
    UNKNOWN
}
