INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(71, 'UNKNOWN', 'Hügieen', 0);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(72, 'UNKNOWN', 'Deodorandid ja lõhnad', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(73, 'UNKNOWN', 'Meeste deodorandid', 72);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(74, 'UNKNOWN', 'Niisutatud salvrätid', 72);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(75, 'UNKNOWN', 'Naiste lõhnad', 72);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(76, 'UNKNOWN', 'Meeste lõhnad', 72);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(77, 'UNKNOWN', 'Naiste deodorandid', 72);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(78, 'UNKNOWN', 'Suuhooldustooted', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(79, 'UNKNOWN', 'Seebid ja dushitooted', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(80, 'UNKNOWN', 'Juuksehooldus', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(81, 'UNKNOWN', 'Kehahooldus', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(82, 'UNKNOWN', 'Intiimhügieen', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(83, 'UNKNOWN', 'Pesuhooldus', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(84, 'UNKNOWN', 'Kodupuhastusained', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(85, 'UNKNOWN', 'Pehmed paberid', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(86, 'UNKNOWN', 'Pakkevahendid', 71);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(87, 'UNKNOWN', 'Hambapastad', 78);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(88, 'UNKNOWN', 'Hambaharjad', 78);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(89, 'UNKNOWN', 'Hambavahetooted', 78);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(90, 'UNKNOWN', 'Suuveed', 78);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(91, 'UNKNOWN', 'Proteesitooted', 78);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(92, 'UNKNOWN', 'Muud suuhooldustooted', 78);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(93, 'UNKNOWN', 'Tükiseebid', 79);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(94, 'UNKNOWN', 'Vedelseebid', 79);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(95, 'UNKNOWN', 'Dušigeelid', 79);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(96, 'UNKNOWN', 'Vannivahud', 79);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(97, 'UNKNOWN', 'Vannitarbed', 79);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(98, 'UNKNOWN', 'Vannisoolad', 79);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(99, 'UNKNOWN', 'Šampoonid', 80);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(223, 'UNKNOWN', 'Juuksepalsamid', 80);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(224, 'UNKNOWN', 'Juukselakid', 80);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(225, 'UNKNOWN', 'Juuksevärvid', 80);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(226, 'UNKNOWN', 'Muud juuksehooldusained', 80);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(227, 'UNKNOWN', 'Juuksevahud', 80);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(228, 'UNKNOWN', 'Juuksegeelid', 80);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(229, 'UNKNOWN', 'Habemeajamisvahud ja geelid', 81);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(230, 'UNKNOWN', 'Vatitooted ja plaastrid', 81);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(231, 'UNKNOWN', 'Näohooldus', 81);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(232, 'UNKNOWN', 'Kehahooldustooted', 81);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(233, 'UNKNOWN', 'Päikesekaitse', 81);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(234, 'UNKNOWN', 'Pesukaitsed', 82);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(235, 'UNKNOWN', 'Sidemed', 82);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(236, 'UNKNOWN', 'Tampoonid', 82);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(237, 'UNKNOWN', 'Inkontinentstooted', 82);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(238, 'UNKNOWN', 'Muud hügieeni tooted', 82);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(239, 'UNKNOWN', 'Pulbrilised pesuvahendid', 83);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(240, 'UNKNOWN', 'Loputusvahendid', 83);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(241, 'UNKNOWN', 'Plekieemaldid', 83);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(242, 'UNKNOWN', 'Valgendus,tekstiilivärvid', 83);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(243, 'UNKNOWN', 'Veepehmendid', 83);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(244, 'UNKNOWN', 'Nõudepesuvahendid', 84);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(245, 'UNKNOWN', 'Üldpuhastusained', 84);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(246, 'UNKNOWN', 'Köögi ja sanit.puhastusained', 84);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(247, 'UNKNOWN', 'Pindade puhastusained', 84);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(248, 'UNKNOWN', 'Eripuhastusained', 84);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(249, 'UNKNOWN', 'Õhuvärskendajad', 84);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(250, 'UNKNOWN', 'Muud kodupuhastusained', 84);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(251, 'UNKNOWN', 'Majapidamispaberid', 85);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(252, 'UNKNOWN', 'Wc-paberid', 85);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(253, 'UNKNOWN', 'Pabertaskurätikud', 85);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(100, 'UNKNOWN', 'Kosmeetika', 0);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(101, 'UNKNOWN', 'Näomeik', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(102, 'UNKNOWN', 'Silmameik', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(103, 'UNKNOWN', 'Huulemeik', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(104, 'UNKNOWN', 'Küünehooldus', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(105, 'UNKNOWN', 'Juukseharjad', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(106, 'UNKNOWN', 'Kammid', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(107, 'UNKNOWN', 'Peeglid', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(108, 'UNKNOWN', 'Kosmeetikavahendid', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(109, 'UNKNOWN', 'Rullid', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(110, 'UNKNOWN', 'Juukseklabrid', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(111, 'UNKNOWN', 'Ehted', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(112, 'UNKNOWN', 'Kosmeetikakotid', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(113, 'UNKNOWN', 'Muud juukse- ja kosm.-tarvikud', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(114, 'UNKNOWN', 'Päikeseprillid', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(115, 'UNKNOWN', 'Muud ehted', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(116, 'UNKNOWN', 'Karbid ja topsid', 100);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(117, 'UNKNOWN', 'Jumestuskreemid', 101);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(118, 'UNKNOWN', 'Puudrid', 101);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(119, 'UNKNOWN', 'Põsepunad', 101);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(120, 'UNKNOWN', 'Muud näomeigitooted', 101);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(121, 'UNKNOWN', 'Peite-,meigialustooted', 101);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(122, 'UNKNOWN', 'Huulevärvid', 102);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(123, 'UNKNOWN', 'Muu huulemeik', 102);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(124, 'UNKNOWN', 'Küünelakieemaldid', 103);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(125, 'UNKNOWN', 'Küünehooldusained', 103);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(126, 'UNKNOWN', 'Küünte eritooted', 103);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(127, 'UNKNOWN', 'Küünelakid', 103);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(128, 'UNKNOWN', 'Kodu', 0);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(129, 'UNKNOWN', 'Lauaküünlad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(130, 'UNKNOWN', 'Läbiva värviga küünlad', 129);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(131, 'UNKNOWN', 'Pealt värvitud pinnaga küünlad', 129);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(132, 'UNKNOWN', 'Lõhnaküünlad', 129);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(133, 'UNKNOWN', 'Teeküünlad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(134, 'UNKNOWN', 'Valged teeküünlad', 133);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(135, 'UNKNOWN', 'Aroomi-teeküünlad', 133);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(136, 'UNKNOWN', 'Klaasküünlad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(137, 'UNKNOWN', 'Klaaslaternad', 136);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(138, 'UNKNOWN', 'Antiik- ja kroonküünlad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(139, 'UNKNOWN', 'Antiikküünlad', 138);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(140, 'UNKNOWN', 'Kroonküünlad', 138);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(141, 'UNKNOWN', 'Õueküünlad ja -laternad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(142, 'UNKNOWN', 'Metallist ümbrises õueküünlad', 141);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(143, 'UNKNOWN', 'Laternaküünlad', 141);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(144, 'UNKNOWN', 'Muud õueküünlad', 141);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(145, 'UNKNOWN', 'Kalmuküünlad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(146, 'UNKNOWN', 'Plastmassist ümbrises kalmuküünlad', 145);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(147, 'UNKNOWN', 'Klaasümbrises kalmuküünlad', 145);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(148, 'UNKNOWN', 'Muud küünlad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(149, 'UNKNOWN', 'Hooaja- ja kujundküünlad', 149);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(150, 'UNKNOWN', 'Muud küünlad', 149);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(151, 'UNKNOWN', 'Köök', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(152, 'UNKNOWN', 'Muud köögiharjad', 151);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(153, 'UNKNOWN', 'Nõudepesuharjad', 151);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(154, 'UNKNOWN', 'Pudeliharjad', 151);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(155, 'UNKNOWN', 'Küürimissvammid', 151);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(156, 'UNKNOWN', 'Vannituba ja wc', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(157, 'UNKNOWN', 'Pesemine', 156);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(158, 'UNKNOWN', 'Muud vannitoa ja wc vahendid', 156);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(159, 'UNKNOWN', 'Aknad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(160, 'UNKNOWN', 'Aknakuivatusvahendid', 159);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(161, 'UNKNOWN', 'Põrandad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(162, 'UNKNOWN', 'Põrandapühkimisvahendid', 161);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(163, 'UNKNOWN', 'Põrandapesu', 161);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(164, 'UNKNOWN', 'Majapidamiskindad', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(165, 'UNKNOWN', 'Kummikindad', 164);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(166, 'UNKNOWN', 'Jäätmehooldus', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(167, 'UNKNOWN', 'Biojäätmed', 166);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(168, 'UNKNOWN', 'Olmejäätmed', 166);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(169, 'UNKNOWN', 'Harjavarred ja muud pühkimistarbed', 128);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(170, 'UNKNOWN', 'Tolmupühkimislapid', 169);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(171, 'UNKNOWN', 'Köök', 0);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(172, 'UNKNOWN', 'Ühekordsed taldrikud', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(173, 'UNKNOWN', 'Ühekordsed joogitopsid', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(174, 'UNKNOWN', 'Ühekordsed söögiriistad', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(175, 'UNKNOWN', 'Ühekordsed laudlinad', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(176, 'UNKNOWN', 'Muud ühekordsed tooted', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(177, 'UNKNOWN', 'Tordipaberid', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(178, 'UNKNOWN', 'Külmutustarvikud', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(179, 'UNKNOWN', 'Toiduvalmistustooted', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(180, 'UNKNOWN', 'Salvrätikud', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(181, 'UNKNOWN', 'Joogikõrred, grilltikud, kokteilitikud', 171);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(182, 'UNKNOWN', 'Lemmikloomad', 0);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(183, 'UNKNOWN', 'Koeratoidud', 182);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(184, 'UNKNOWN', 'Kassitoidud', 182);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(185, 'UNKNOWN', 'Muude loomade toidud', 182);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(186, 'UNKNOWN', 'Lemmikloomade maiused', 182);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(187, 'UNKNOWN', 'Lemmikloomade tarvikud', 182);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(188, 'UNKNOWN', 'Lemmikloomade lelud', 182);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(189, 'UNKNOWN', 'Lapsed', 0);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(190, 'UNKNOWN', 'Maiustused, jäätised, snäkid', 0);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(191, 'UNKNOWN', 'Külmutatud tooted', 0);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(192, 'UNKNOWN', 'Lastejoogid', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(193, 'UNKNOWN', 'Laste kuivtoit', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(194, 'UNKNOWN', 'Laste valmistoit', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(195, 'UNKNOWN', 'Teipmähkmed', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(196, 'UNKNOWN', 'Püksmähkmed', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(197, 'UNKNOWN', 'Erimähkmed', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(198, 'UNKNOWN', 'Lutid ja lutiketid', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(199, 'UNKNOWN', 'Lutipudelid ja tarvikud', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(200, 'UNKNOWN', 'Imetamistooted', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(201, 'UNKNOWN', 'Jätkupiimasegud', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(202, 'UNKNOWN', 'Muud beebihooldustooted', 189);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(203, 'UNKNOWN', 'Krõpsud', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(204, 'UNKNOWN', 'Snäkid', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(205, 'UNKNOWN', 'Kommikotid', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(206, 'UNKNOWN', 'Kommikarbid', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(207, 'UNKNOWN', 'Närimiskummid', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(208, 'UNKNOWN', 'Väikesed maiustused', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(209, 'UNKNOWN', 'Mitmesugused maiustused', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(210, 'UNKNOWN', 'Hooajalised maiustused', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(211, 'UNKNOWN', 'Jäätis', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(212, 'UNKNOWN', 'Šokolaadibatoonid', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(213, 'UNKNOWN', 'Šokolaaditahvlid', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(214, 'UNKNOWN', 'Muud šokolaaditooted', 190);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(215, 'UNKNOWN', 'Külmutatud liha ja lihapooltooted', 191);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(216, 'UNKNOWN', 'Külmutatud kala ja mereannid', 191);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(217, 'UNKNOWN', 'Külmutatud aedvili ja kartulid', 191);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(218, 'UNKNOWN', 'Külmutatud valmistoit', 191);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(219, 'UNKNOWN', 'Külmutatud pagaritooted', 191);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(220, 'UNKNOWN', 'Külmutatud puuviljad, marjad', 191);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(221, 'UNKNOWN', 'Jäätis', 191);
INSERT INTO category (id, category_type_code, "name", parent_category_id) VALUES(222, 'UNKNOWN', 'Tervisetooted', 0);







