version: 0.2

phases:
  install:
    commands:
      - if [ -d price-comparison-client1 ]; then cd price-comparison-client1/; fi
      - npm install
  build:
    commands:
      - if [ -d price-comparison-client1 ]; then cd price-comparison-client1/; fi
      - npm run build
      - aws s3 sync ./dist s3://s3-eu-west-1.amazonaws.com/price-comparison-web
artifacts:
  files:
    - 'price-comparison-client1/dist/**/*'
    - 'dist/**/*'
