# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy client application to Amazon ECS

on:
  push:
    branches:
      - main

env:
  WORK_DIR: price-comparison-client1
  AWS_REGION: eu-west-1
  DIST_LOCATION_CODE: ./dist

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - "${{ env.WORK_DIR }}/**"

      - name: Early exit
        if: steps.changes.outputs.src != 'true'
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run install
        working-directory: ${{ env.WORK_DIR }}
        run: npm install

      - name: Run build
        working-directory: ${{ env.WORK_DIR }}
        run: npm run build

      - name: Deploying application to Amazon S3
        uses: dvelasquez/deploy-s3-action@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          # BUCKET_PATH: "/pr/${{github.event.number}}"
          BUCKET_PATH: ""
          DIST_LOCATION_CODE: ./dist
