package com.shopleech.contract;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "sl-user")
public class AppUser {

    @DynamoDBAutoGeneratedKey
    String id;
    @DynamoDBHashKey
    String username;
    @DynamoDBAttribute
    String password;
    @DynamoDBAttribute
    String name;
    @DynamoDBAttribute
    LocalDateTime createdAt;
    @DynamoDBAttribute
    String createdBy;
    @DynamoDBAttribute
    LocalDateTime modifiedAt;
    @DynamoDBAttribute
    String modifiedBy;

    public AppUser(String username, String password){
        this.username = username;
        this.password = password;
    }

    public AppUser(String id, String username, String password, String name) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return "App should return a greeting";
    }
}
